import type { Metadata } from "next";
import SideAndNav from "./components/SideAndNav";
import "@radix-ui/themes/styles.css";
import "./globals.css";
import {
  Theme
  // ThemePanel 
} from "@radix-ui/themes";
import { Toaster } from "react-hot-toast";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body suppressHydrationWarning={true}>
        <Theme accentColor="crimson" grayColor="sand" radius="large" scaling="95%">
          <Toaster
            position="top-center"
            reverseOrder={false}
          />
          <SideAndNav>

            {children}
          </SideAndNav>
        </Theme>
      </body>
    </html>
  );
}
